# Generated by Django 5.0.6 on 2024-05-29 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Rating must be at least 0.'), django.core.validators.MaxValueValidator(5, message='Rating must be at most 5.')]),
        ),
    ]
