# Generated by Django 5.0.6 on 2024-05-29 14:59

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[recipes.models.validate_rating]),
        ),
    ]
